### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by jdmarshall** [eguneys/generator-emberfs#2]
Error: Cannot find module '../../util.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/username/my_npm/lib/node_modules/generator-emberfs/generators/app/index.js:5:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

I'm looking at your node_modules directory, there is no utils.js in that location
node_modules/generator-emberfs:
README.md	generators	node_modules	package.json
node_modules/generator-emberfs/generators:
app		controller	route		test
component	model		template

**Comment by frankcash** [comment]
`..` Means go up a directory, so what it is saying is go up two directories from `/generators/app/` which puts the application at the `/` directory

**Comment by jdmarshall** [comment]
Yeah.  The package.json doesn't include /utils.js in the output.  So the tests pass locally, but on npm install the file is missing.  See my pull request for the fix.
