### ISSUE TITLE
Error on running "yo emberfs"

### ISSUE THREAD

**Issue by tahniyatkazmi** [eguneys/generator-emberfs#6]
I am getting following error while running **yo emberfs**
Error: Cannot find module '../../util.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/adnan/.nvm/v0.10.29/lib/node_modules/generator-emberfs/generators/app/index.js:5:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

I have used following versions of npm
  * 1.4.14
  * 2.0.0

**Comment by enjine** [comment]
Same issue here.
Interested in contrasting this approach with the ember-cli approach. 

$ npm --version
2.6.0
$ node --version
v0.12.0
